name: Publish Module

# Will remove before merge and make it only tags
on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  publish-package:
    runs-on: ubuntu-latest
    steps:
      - name: Free GH runner space
        run: |
          df -h
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          sudo docker image prune --all --force
          df -h

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org"
          cache: "npm"

      - name: Install Node Packages
        run: npm ci
        working-directory: .

      - name: Build Module
        run: npx pepr build
        working-directory: .

      - name: Change Module Package Name
        id: updatedzarfyaml
        uses: mikefarah/yq@master
        with:
          cmd: yq -i '.metadata.name = "dubbd-pepr"' zarf.yaml

      - name: Create Package
        uses: ./.github/actions/create-zarf-package
        with:
          working-dir: /dist

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Zarf Package
        run: zarf package publish zarf-package-*.tar.zst oci://ghcr.io/TristanHoladay/packages
        working-directory: /dist
        timeout-minutes: 60
