name: Create Zarf Package
description: Creates a Zarf package for the requested path

inputs:
  working-dir:
    description: Zarf package path
    required: true

outputs:
  latest-package-version:
    description: The latest package version
    value: ${{ steps.latest-package-version.outputs.latest-package-version }}

runs:
  using: composite
  steps:
    - name: Install Zarf
      uses: defenseunicorns/setup-zarf@main
      with:
        # renovate: datasource=github-tags depName=defenseunicorns/zarf versioning=semver
        version: v0.30.1
        download-init-package: false

    - name: Create Zarf Package
      shell: bash
      run: zarf package create --confirm
      working-directory: ${{ inputs.working-dir }}
